<a href="https://colab.research.google.com/github/vidyasagarcrj/Codedirect/blob/main/Questions_HuggingFace_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem Statement

1. 🛠️ The overall problem is to develop a text classification system using a pre-trained DistilBert model that can accurately predict categories based on textual input.

2. 📝 The input feature, denoted as 'X', consists of raw text strings sourced from a dataset, which the model processes to predict categorical labels.

3. 🎯 The target variable, referred to as 'label', represents the actual categories of the text, which are used to train the model and evaluate its accuracy.

4. 📊 The model's performance is assessed through metrics such as the confusion matrix and accuracy, comparing the predicted labels against the actual labels.

5. 🔧 The project involves not only fine-tuning a pre-trained language model on a specific dataset but also validating its effectiveness on both a smaller sample and a larger subset to ensure robustness and scalability of the predictions.

#Install the necessary libraries



1. **Install Accelerate**:
2. **Install Transformers and Datasets**:
3. **Upgrade PyArrow**:

Import Libraries

1. **Import Standard Data Science Libraries**:
3. **Import PyTorch and Transformers for NLP**:



In [ ]:
## Write your code here

In [1]:
!pip -q install accelerate -U
!pip -q install transformers[torch]
!pip -q install datasets
#Restart after installing

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 15.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 8.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from transformers import pipeline

In [3]:
# Textwrp function to display the output in a better format
# This is an optional function, you can ignore it
from IPython.display import HTML, display

def wrap_display():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', wrap_display)

# Import Emotions Data. Target variable is 'Label'

Import the data from https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Final_Emotion_Data/five_emotions_data.csv

Display the first few rows of the dataset to understand its structure

In [ ]:
## Write your code here

In [4]:
import pandas as pd
emotion_data=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Final_Emotion_Data/five_emotions_data.csv")
emotion_data.head()

Id    Emotion                                               Text  label
0   1    sadness                            i didnt feel humiliated      3
1   2    sadness  i can go from feeling so hopeless to so damned...      3
2   4       love  i am ever feeling nostalgic about the fireplac...      1
3   6    sadness  ive been feeling a little burdened lately wasn...      3
4   9  happiness  i have been with petronas for years i feel tha...      0

In [5]:
emotion_data.shape

(42645, 4)

# Use distilbert model without finetunung

Here are concise instructions to write and execute the Python code you provided, which utilizes a pre-trained DistilBERT model from the `transformers` library for text classification without fine-tuning:

Step 1: Install and Import Libraries
1. **Install the necessary Python packages** if they're not already installed:

2. **Import the libraries** in your Python script:


 Step 2: Set Up the DistilBERT Model
1. **Initialize the DistilBERT pipeline** for text classification. Ensure you have GPU support (CUDA) if available:


 Step 3: Prepare and Predict with Your Dataset
1. **Sample and preprocess the dataset**:
   - Assuming `emotions_data` is already loaded:

2. **Classify text** using the model and extract predictions:


Step 4: Evaluate Model Performance
1. **Calculate and print the confusion matrix** and accuracy:




In [ ]:
## Write your code here

In [17]:
emotion_model = pipeline(task="sentiment-analysis",
                         model="bhadresh-savani/distilbert-base-uncased-emotion",
                         device="cuda")

Device set to use cuda


RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [5]:
# Distil bert model
from transformers import pipeline
emotion_model = pipeline(task="sentiment-analysis",
                            model="distilbert-base-uncased"
                            )


/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Device set to use cuda:0


In [7]:
sample_data=emotion_data.sample(100, random_state=42)
sample_data.head()

Id  Emotion                                               Text  \
1900    2690  sadness  i social and dreaming about things that make y...   
20627  27544    worry  is missing training tonight, the lurgy is on m...   
12481  17415    worry               my HD is full. need to cleanup a lot   
30267  39810  sadness  i'm watching missing pieces, just coz the them...   
14420  19838  sadness          rain got so big weather so cold right now   

       label  
1900       3  
20627      4  
12481      4  
30267      3  
14420      3

In [9]:
sample_data["label"].nunique()

5

In [10]:
sample_data=emotion_data.sample(100, random_state=42)
sample_data["Text"]=sample_data["Text"].apply(lambda x: " ".join(x.split()[:350]))
sample_data["emotion_model"] = sample_data["Text"].apply(lambda x: emotion_model(x)[0]["label"])
#Default prediction is not a number LABEL_1, LABEL_0
sample_data["emotion_model_num"]=sample_data["emotion_model"].apply(lambda x: x[-1])
sample_data["emotion_model_num"] = sample_data["emotion_model_num"].astype(int)
sample_data.head()

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset


Id  Emotion                                               Text  \
1900    2690  sadness  i social and dreaming about things that make y...   
20627  27544    worry  is missing training tonight, the lurgy is on m...   
12481  17415    worry               my HD is full. need to cleanup a lot   
30267  39810  sadness  i'm watching missing pieces, just coz the them...   
14420  19838  sadness          rain got so big weather so cold right now   

       label emotion_model  emotion_model_num  
1900       3       LABEL_0                  0  
20627      4       LABEL_0                  0  
12481      4       LABEL_0                  0  
30267      3       LABEL_0                  0  
14420      3       LABEL_0                  0

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(sample_data["label"], sample_data["emotion_model_num"])
print(cm)
accuracy=cm.diagonal().sum()/cm.sum()
print(accuracy)

[[33  4  0  0  0]
 [ 7  0  0  0  0]
 [12  1  0  0  0]
 [19  1  0  0  0]
 [22  1  0  0  0]]
0.33


# Finetuning the model with our data


1. Begin by importing necessary libraries including `DistilBertTokenizer` and `DistilBertForSequenceClassification` from `transformers`, `load_dataset`, `DatasetDict`, `ClassLabel`, and `Dataset` from `datasets`, `pandas`, `train_test_split` from `sklearn.model_selection`, and `torch`.

2. Load your sample data into a pandas DataFrame, `sample_data`.

3. Convert the DataFrame into a `Dataset` object using `Dataset.from_pandas()` method.

4. Split the data into training and testing sets using the `train_test_split` method from the `datasets` library, setting aside 20% of the data for testing.

5. Create a `DatasetDict` to organize the datasets into 'train' and 'test' subsets.

6. Load the `DistilBertTokenizer` from the `transformers` library using the pretrained 'distilbert-base-uncased' model.

7. Set the tokenizer's padding token to the end-of-sequence token and update the padding token ID accordingly. Add a special padding token '[PAD]' to the tokenizer.

8. Define a function, `tokenize_function`, that tokenizes the texts in the dataset. Ensure the texts are padded to a maximum length of 100 characters and truncated if necessary.

9. Apply the `tokenize_function` to the datasets using the `.map()` method with `batched=True` to process batches of texts at once.

In [ ]:
#Write your code here

In [12]:
TRN_data=emotion_data

In [13]:
TRN_data

Id    Emotion                                               Text  \
0          1    sadness                            i didnt feel humiliated   
1          2    sadness  i can go from feeling so hopeless to so damned...   
2          4       love  i am ever feeling nostalgic about the fireplac...   
3          6    sadness  ive been feeling a little burdened lately wasn...   
4          9  happiness  i have been with petronas for years i feel tha...   
...      ...        ...                                                ...   
42640  55996    neutral                                   @JohnLloydTaylor   
42641  55997       love                     Happy Mothers Day  All my love   
42642  55998       love  Happy Mother's Day to all the mommies out ther...   
42643  55999  happiness  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...   
42644  56000       love  @mopedronin bullet train from tokyo    the gf ...   

       label  
0          3  
1          3  
2          1  
3          3  
4          0  
...      ...  
42640      2  
42641      1  
42642      1  
42643      0  
42644      1  

[42645 rows x 4 columns]

In [7]:
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from transformers import Trainer, TrainingArguments
from datasets import load_dataset, DatasetDict, ClassLabel, Dataset
import pandas as pd
from sklearn.model_selection import train_test_split
import torch

In [14]:
print(TRN_data.columns)

Index(['Id', 'Emotion', 'Text', 'label'], dtype='object')


In [15]:
TRN_DATA = Dataset.from_pandas(TRN_data)
# Split the dataset into training and testing sets
train_test_split = TRN_DATA.train_test_split(test_size=0.2)  # 80% training, 20% testing
dataset = DatasetDict({
    'train': train_test_split['train'],
    'test': train_test_split['test']
})
dataset

DatasetDict({
    train: Dataset({
        features: ['Id', 'Emotion', 'Text', 'label'],
        num_rows: 34116
    })
    test: Dataset({
        features: ['Id', 'Emotion', 'Text', 'label'],
        num_rows: 8529
    })
})

In [16]:
# Load the tokenizer
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Padding
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.add_special_tokens({'pad_token': '[PAD]'} )

def tokenize_function(examples):
    return tokenizer(examples["Text"], padding="max_length", truncation=True, max_length=512)
tokenized_datasets = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/34116 [00:00<?, ? examples/s]

Map:   0%|          | 0/8529 [00:00<?, ? examples/s]

In [17]:
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased',
                                                            num_labels=5,
                                                            pad_token_id=tokenizer.eos_token_id) # Adjust num_labels as needed
model

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (li

In [18]:
training_args = TrainingArguments(
    output_dir="./results_bert_custom",
    num_train_epochs=1,
    logging_dir="./logs_bert_custom",
    evaluation_strategy="epoch",
)

# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['test'],
)

# Start training
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


<IPython.core.display.Javascript object>

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


TrainOutput(global_step=4265, training_loss=1.0051070755559424, metrics={'train_runtime': 1944.2759, 'train_samples_per_second': 17.547, 'train_steps_per_second': 2.194, 'total_flos': 4519499556188160.0, 'train_loss': 1.0051070755559424, 'epoch': 1.0})

## Load and Train the model

1. Load the `DistilBertForSequenceClassification` model from the `transformers` library, using the pretrained 'distilbert-base-uncased' model. Specify `num_labels` based on your classification needs and set `pad_token_id` to the tokenizer's end-of-sequence token ID.

2. Set up the training configuration using `TrainingArguments`. Define an `output_dir` for storing training results, set `num_train_epochs` for the number of training epochs, specify a `logging_dir` for training logs, and choose `evaluation_strategy` as 'epoch' to perform evaluations at the end of each epoch.

3. Initialize a `Trainer` object with the model, training arguments, and datasets for training and evaluation. Specify the training dataset using `tokenized_datasets['train']` and the evaluation dataset as `tokenized_datasets['test']`.

4. Begin the training process by invoking the `train()` method on the `Trainer`.

5. Specify a directory where you want to save both the trained model and the tokenizer, e.g., "./distilbert_finetuned".

6. Save the trained model and tokenizer to the specified directory using the `save_pretrained()` method for both the model and tokenizer.

7. Additionally, save the model to another directory or under another name using the `save_model()` method of the `Trainer`.

8. Compress the model directory into a ZIP file using a zip utility, specifying the target directory and the name for the ZIP file, e.g., "distilbert_finetuned_10k.zip".

In [37]:
# Define the directory where you want to save your model and tokenizer
model_dir = "./distilbert_finetuned"

# Save the model
model.save_pretrained(model_dir)

# Save the tokenizer
tokenizer.save_pretrained(model_dir)

#Save the model with
trainer.save_model('Distilbert_Custom_emotions_label5')

## Make Predictions

1. Define a function, `make_prediction`, which takes a single text string as input. Inside this function:
   - Tokenize the text using your pretrained tokenizer. Specify that tensors should be returned as PyTorch tensors (`return_tensors="pt"`).
   - Send the tokenized inputs to a CUDA device for GPU acceleration.
   - Pass the inputs to your pretrained model and obtain the outputs.
   - Extract the logits from the outputs and determine the predicted class by finding the index of the maximum logit value.
   - Convert the prediction tensor from GPU to CPU and transform it into a numpy array.
   - Return the prediction.

2. Apply the `make_prediction` function to the "Text" column of your `sample_data` DataFrame, extracting the first element of the returned array to a new column named `finetuned_predicted`.

3. Calculate the confusion matrix using `confusion_matrix` from `sklearn.metrics`, comparing the actual labels and the predicted labels from your DataFrame. Print the resulting confusion matrix.

4. Compute and print the accuracy of your predictions by dividing the sum of the diagonal elements of the confusion matrix by the total number of predictions.

5. Select a large subset (e.g., 40,000 samples) from another dataset (assumed to be `emotions_data` here), using a fixed random state for reproducibility.

6. Apply the `make_prediction` function to the "Text" column of this large dataset, storing the results in a new column named `finetuned_predicted`.

7. Calculate and print the confusion matrix for this larger dataset to compare the predicted labels against the actual labels.

8. Compute and print the accuracy for this dataset in the same manner as described above.

In [70]:
def make_prediction(text):
  new_complaint=text
  inputs=tokenizer(new_complaint, return_tensors="pt")
  inputs = inputs.to(torch.device("cuda:0"))
  outputs=model(**inputs)
  predictions=outputs.logits.argmax(-1)
  predictions=predictions.detach().cpu().numpy()
  return(predictions)

sample_data["finetuned_predicted"]=sample_data["Text"].apply(lambda x: make_prediction(str(x))[0])
sample_data.sample(10)

Id    Emotion                                               Text  \
323      459  happiness  i feel after reading allthingsbucks blog which...   
23440  31067    sadness  Charter is pissing me off, the rest of the int...   
17873  24124  happiness  @HannahSukter anywayss to the point i am dying...   
17859  24108    neutral   JUST GOT BACK 4RM A LONG WORKOUT AT DA GYM  ....   
36389  47890      worry  @sodaly you are welcome  @pamslim's book is a ...   
12617  17581    sadness           Today feels like friday. Too bad its not   
20015  26802    neutral  Grilled again for dinner last night for the se...   
39618  52081  happiness  @tommcfly i saw you on tues and last niiiighht...   
25419  33594      worry  @jarnmang  Hope everything ok! Can burr fix this?   
21549  28720      worry  @gfalcone601 I know right  Poorpoor girl! It s...   

       label  finetuned_predicted  
323        0                    3  
23440      3                    4  
17873      0                    4  
17859      2                    2  
36389      4                    0  
12617      3                    3  
20015      2                    0  
39618      0                    4  
25419      4                    2  
21549      4                    4

In [22]:
def make_prediction(text):
  new_complaint=text
  inputs=tokenizer(new_complaint, return_tensors="pt")
  inputs = inputs.to(torch.device("cuda:0"))
  outputs=model(**inputs)
  predictions=outputs.logits.argmax(-1)
  predictions=predictions.detach().cpu().numpy()
  return(predictions)

sample_data_large["finetuned_predicted"]=sample_data_large["Text"].apply(lambda x: make_prediction(str(x))[0])
sample_data_large.sample(10)

Id    Emotion                                               Text  \
28407  37375  happiness                              @donatoclassic me too   
34485  45352    neutral  @BreeOlson9 I see your date is showing you a g...   
16149  21979    sadness  am about to sell my Medieval trading pavillion...   
41495  54514  happiness   @AgonisingNewt morning Newt...hope you are well!   
40294  52955    neutral  www.youtube.com/user/sammyandchellishow       ...   
2018    2858  happiness                        i feel he was eager to help   
8002   11278  happiness  i choose mouse because i feel cute as of now t...   
23080  30619    neutral  @Mali_Marls Nah I got bare work to do, 3 weeks...   
19677  26397      worry  dissapointed in every way....confused... and d...   
34671  45591  happiness  @morgandonovan Haha, nice! ;) Thanks for letti...   

       label  finetuned_predicted  
28407      0                    2  
34485      2                    0  
16149      3                    3  
41495      0                    4  
40294      2                    2  
2018       0                    0  
8002       0                    0  
23080      2                    2  
19677      4                    3  
34671      0                    0

In [23]:
from sklearn.metrics import confusion_matrix
# Create the confusion matrix
cm1 = confusion_matrix(sample_data_large["label"], sample_data_large["finetuned_predicted"])
print(cm1)
accuracy1=cm1.diagonal().sum()/cm1.sum()
print(accuracy1)

[[194  20  20   4   7]
 [ 27  66  10   3   6]
 [ 21   3 116  11  34]
 [  4   3  10 169  53]
 [ 16   2  31  41 129]]
0.674


In [25]:
sample_data=emotion_data
sample_data.head()

Id    Emotion                                               Text  label  \
0   1    sadness                            i didnt feel humiliated      3   
1   2    sadness  i can go from feeling so hopeless to so damned...      3   
2   4       love  i am ever feeling nostalgic about the fireplac...      1   
3   6    sadness  ive been feeling a little burdened lately wasn...      3   
4   9  happiness  i have been with petronas for years i feel tha...      0   

   finetuned_predicted  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0

In [26]:
sample_data=emotion_data.sample(1000, random_state=42)
sample_data.head()

Id  Emotion                                               Text  \
1900    2690  sadness  i social and dreaming about things that make y...   
20627  27544    worry  is missing training tonight, the lurgy is on m...   
12481  17415    worry               my HD is full. need to cleanup a lot   
30267  39810  sadness  i'm watching missing pieces, just coz the them...   
14420  19838  sadness          rain got so big weather so cold right now   

       label  finetuned_predicted  
1900       3                    0  
20627      4                    0  
12481      4                    0  
30267      3                    0  
14420      3                    0

In [39]:
#Code to donwloading the distilbert model
!gdown --id 1785J3ir19RaZP3ebbFvWUX88PMaBouro -O Distilbert_Custom_emotions_label5.zip
!unzip -o -j distilbert_finetuned_V1.zip -d Distilbert_Custom_emotions_label5

model_v1 = DistilBertForSequenceClassification.from_pretrained('/content/Distilbert_Custom_emotions_label5')
model_v1.to("cuda:0")

/usr/local/lib/python3.10/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): https://drive.google.com/uc?id=1785J3ir19RaZP3ebbFvWUX88PMaBouro
From (redirected): https://drive.google.com/uc?id=1785J3ir19RaZP3ebbFvWUX88PMaBouro&confirm=t&uuid=9dfe85eb-b949-4db2-be70-6da0bdce515c
To: /content/Distilbert_Custom_emotions_label5.zip
100% 247M/247M [00:05<00:00, 44.0MB/s]
Archive:  distilbert_finetuned_V1.zip
  inflating: Distilbert_Custom_emotions_label5/config.json  
  inflating: Distilbert_Custom_emotions_label5/model.safetensors  
  inflating: Distilbert_Custom_emotions_label5/special_tokens_map.json  
  inflating: Distilbert_Custom_emotions_label5/tokenizer_config.json  
  inflating: Distilbert_Custom_emotions_label5/vocab.txt  


DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (li

In [40]:
def make_prediction(text):
  new_complaint=text
  inputs=tokenizer(new_complaint, return_tensors="pt")
  inputs = inputs.to(torch.device("cuda:0"))
  outputs=model_v1(**inputs)
  predictions=outputs.logits.argmax(-1)
  predictions=predictions.detach().cpu().numpy()
  return(predictions)


In [20]:
sample_data_large=emotion_data.sample(n=1000, random_state=55)
sample_data_large["finetuned_predicted"]=sample_data_large["Text"].apply(lambda x: make_prediction(str(x)[:350])[0])

In [43]:
sample_data_large["finetuned_predicted"]

1749     1
6225     0
28661    1
39023    0
3597     1
        ..
34780    1
36639    0
34320    1
9608     1
32565    1
Name: finetuned_predicted, Length: 1000, dtype: int64